# Generated by Django 5.2.6 on 2025-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll",
            field=models.IntegerField(),
        ),
    ]
